Parameters:
  TransitGatewayAttachmentId:
    Type: String
    Description: The ID of the attachment to the target VPC
  TransitGatewayRouteTableId:
    Type: String
    Description: The ID of the route table for the transit gateway

Resources:
  TransitGatewayRouteTableAssociation:
    Type: AWS::EC2::TransitGatewayRouteTableAssociation
    Properties:
      TransitGatewayAttachmentId: !Ref TransitGatewayAttachmentId
      TransitGatewayRouteTableId: !Ref TransitGatewayRouteTableId